# FedAvg strategy configuration yaml file
_target_: flwr.server.strategy.FedAvg

fraction_fit: 0.00001
min_fit_clients: ${num_clients_per_round_fit}
fraction_evaluate: 0.00001
min_evaluate_clients: ${num_clients_per_round_eval}
min_available_clients: ${num_clients}

on_fit_config_fn:
  _target_: server.get_on_fit_config
  cfg: ${client_config}

evaluate_fn:
  _target_: server.get_evaluate_fn
  model: ${model}
  dataloader: ${dataloaders}
  criterion: ${criterion}
  metric: ${metric}

fit_metrics_aggregation_fn:
  _target_: server.get_fit_metrics_aggregation_fn

evaluate_metrics_aggregation_fn:
  _target_: server.get_fit_metrics_aggregation_fn