name: flower
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9.0
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.6
  - pip
  - pip:
      - flwr==1.3.0
      - ray==1.11.1
      - segmentation-models-pytorch==0.3.4
      - matplotlib==3.9.4
      - opencv-contrib-python==4.10.0.84
      - pandas==2.2.3
      - Jinja2==3.1.5
      - albumentations==1.3.0
      - gdown==5.2.0
      - wandb==0.19.11
      - pydantic==1.10.12
      - omegaconf==2.3.0
      - hydra-core==1.3.2
