num_clients: 2

num_cpus: 2
num_gpus: 0.5

num_clients_per_round_fit: 1
num_clients_per_round_eval: 1
batch_size: 2
patch_size: 192
num_rounds: 2
num_classes: 6

smooth: 1.0        # Smooth term to avoid division by zero
ignore_index: null # FIXME: ADD the backgourd "6/-1" Use None if no pixels should be ignored
log_loss: false    # Set True if you want to compute -log(dice_coeff) instead of 1 - dice_coeff

defaults:
  - model: Unet
  - strategy: FedAvg
  - criterion: CombinedLoss
  - metric: MeanIoU
  - DiceLoss: DiceLoss
  - FocalLoss: FocalLoss
  - LovaszLoss: LovaszLoss
  
dataloaders:
  _target_: PanNuke.load_data
  batch_size: ${batch_size}


client_config:
  local_epochs: 2
  lr: 0.01
  step_size: 7
  gamma: 0.1
  save_dir: ./saved_models
