client_config:
  local_epochs: 2
  lr: 0.01
  step_size: 7
  gamma: 0.1
  save_dir: ./saved_models


num_clients: 4
num_rounds: 2

num_cpus: 2
num_gpus: 1

num_clients_per_round_fit: ${num_clients}
num_clients_per_round_eval: ${num_clients}
batch_size: 3

smooth: 1.0        # Smooth term to avoid division by zero
ignore_index: null # FIXME: ADD the backgourd "6/-1" Use None if no pixels should be ignored
log_loss: false    # Set True if you want to compute -log(dice_coeff) instead of 1 - dice_coeff

defaults:
  - model: Segformer
  - strategy: FedAvg
  - criterion: DiceLoss
  - MeanIoU: MeanIoU
  - MeanDice: MeanDice
  - DiceLoss: DiceLoss
  - FocalLoss: FocalLoss
  - LovaszLoss: LovaszLoss
  
dataloaders:
  _target_: PanNuke.load_data
  batch_size: ${batch_size}


num_classes: 6
patch_size: 192
