client_config:
  local_epochs: 30
  lr: 0.01
  step_size: 7
  gamma: 0.1
  save_dir: ./saved_models

num_clients: 4
num_rounds: 3

num_cpus: 8
num_gpus: 1

num_clients_per_round_fit: ${num_clients}
num_clients_per_round_eval: ${num_clients}
batch_size: 2

# Losses configuration
smooth: 1        # Smooth term to avoid division by zero for all the losses and metrics
ignore_index: 5  # FIXME: ADD the backgourd "6/-1" Use None if no pixels should be ignored
log_loss: false  # Set True if you want to compute -log(dice_coeff) instead of 1 - dice_coeff

# LovaszLoss
per_image: true    # If True loss computed per each image and then averaged, else computed per whole batch

# FocalLoss
alpha: 0.25
gamma: 2.0
reduction: mean
normalized: true
reduced_threshold: null

defaults:
  - _self_
  - model: unet
  - strategy: FedAvg
  - criterion: CombinedLoss
  - DiceLoss: DiceLoss
  - FocalLoss: FocalLoss
  - LovaszLoss: LovaszLoss
  - metrics: metrics
  
dataloaders:
  _target_: PanNuke.load_data
  batch_size: ${batch_size}


num_classes: 6
patch_size: 192
