_target_: segmentation_models_pytorch.losses.FocalLoss
mode: multilabel
alpha: ${alpha}
gamma: ${gamma}
ignore_index: ${ignore_index}
reduction: ${reduction}
normalized: ${normalized}
reduced_threshold: ${reduced_threshold}