_target_: Models.Segformer           # Model class
encoder_name: efficientnet-b4        # Name of the encoder
encoder_depth: 5                     # in range [3, 5]
encoder_weights: imagenet            # Pre-trained weights
decoder_segmentation_channels: 256   # Number of decoder channels
in_channels: 3                       # Number of input channels
classes: 6                           # Number of classes
activation: softmax2d                # None for logits & 'softmax2d' for multiclass segmentation