_target_: segmentation_models_pytorch.Unet  # Model class
encoder_name: mit_b0                        # Name of the encoder
encoder_weights: imagenet                   # Pre-trained weights
in_channels: 3                              # Number of input channels
classes: 6                                  # Number of classes
activation: softmax2d                       # Activation function (use None for logits)